### ISSUE TITLE
Scripted plugins

### ISSUE THREAD

**Issue by fntlnz** [drone/drone-plugin-go#3]
I thought that could be a very good thing to allow write plugins using a scripting language like javascript, lua or even python.

For instance for javascript you could use [robertkrimen/otto](https://github.com/robertkrimen/otto) to parse the javascript.

Of course the most difficult thing is the part to define and implement the final API to hook into the build lifecycle.

What do you think?

**Comment by bradrydzewski** [comment]
@fntlnz this isn't fully documented yet, since 0.4 isn't released, but plugins are just Docker containers that accept a specific JSON input. So you can write a plugin for Drone in any language you want, as long as it runs in a Docker container and accepts the right JSON input.

You can see an example on the JSON input here:
https://github.com/drone-plugins/drone-slack

This library (`drone-plugin-go`) provides a set of helper functions for writing plugins in Go. I see no reason we couldn't have similar libraries for other languages (ie `drone-plugin-node`) to simplify plugin development. If you are experienced with Node (or another language) and would like to port this library I would be happy to include it as an official plugin api. We can discuss further in the gitter.im/drone/drone chat room

But bottom line is, you can write plugins in any language you want :)

**Comment by fntlnz** [comment]
Thank you for the clarification. This is definitely better than what i'd expected!

 :)
